export type Screen = "home" | "create" | "gallery" | "wallet" | "subscription";
export type Lang = "ru" | "en";

export const T = {
  ru: {
    appName: "Mintify",
    tagline: "Создавай. Коллекционируй. Продавай.",
    home: "Главная",
    create: "Создать",
    gallery: "Стили",
    wallet: "Кошелёк",
    subscription: "Pro",
    greeting: "Добро пожаловать",
    homeSubtitle: "Твоя NFT-студия в кармане",
    createCollection: "Создать коллекцию",
    myNfts: "Мои NFT",
    sub: "Подписка",
    marketplace: "Маркетплейс",
    totalNfts: "NFT создано",
    totalCollections: "Коллекций",
    totalSales: "Продаж",
    featuredTitle: "Трендовые коллекции",
    seeAll: "Все",
    createTitle: "Новая коллекция",
    createSubtitle: "Настрой и сгенерируй свои NFT",
    chooseStyle: "Выбери стиль",
    nftCount: "Количество NFT",
    generate: "Генерировать",
    galleryTitle: "Галерея стилей",
    gallerySubtitle: "Выбери базу для коллекции",
    freeStyles: "Бесплатные стили",
    proStyles: "Pro стили",
    locked: "Заблокировано",
    unlockPro: "Открыть Pro →",
    walletTitle: "Кошелёк",
    walletSubtitle: "Твои коллекции и активы",
    myCollections: "Мои коллекции",
    balance: "Баланс",
    forSale: "На продаже",
    sold: "Продано",
    items: "шт.",
    subTitle: "Mintify Pro",
    subSubtitle: "Раскрой полный потенциал",
    monthly: "Месяц",
    yearly: "Год",
    save: "−40%",
    proFeatures: ["Все Pro стили", "Неограниченные NFT", "Приоритет генерации", "0% комиссии в маркетплейсе", "Аналитика коллекций", "Поддержка 24/7"],
    freeFeatures: ["5 бесплатных стилей", "До 10 NFT в месяц", "Базовый маркетплейс"],
    buyPro: "Купить Pro",
    currentPlan: "Текущий план",
    freePlan: "Бесплатный",
    perMonth: "/ мес",
    perYear: "/ год",
    price1: "390 ₽",
    price2: "2 790 ₽",
  },
  en: {
    appName: "Mintify",
    tagline: "Create. Collect. Sell.",
    home: "Home",
    create: "Create",
    gallery: "Styles",
    wallet: "Wallet",
    subscription: "Pro",
    greeting: "Welcome back",
    homeSubtitle: "Your NFT studio in your pocket",
    createCollection: "Create Collection",
    myNfts: "My NFTs",
    sub: "Subscription",
    marketplace: "Marketplace",
    totalNfts: "NFTs minted",
    totalCollections: "Collections",
    totalSales: "Sales",
    featuredTitle: "Trending Collections",
    seeAll: "See all",
    createTitle: "New Collection",
    createSubtitle: "Configure and generate your NFTs",
    chooseStyle: "Choose Style",
    nftCount: "NFT Count",
    generate: "Generate",
    galleryTitle: "Style Gallery",
    gallerySubtitle: "Choose a base for your collection",
    freeStyles: "Free Styles",
    proStyles: "Pro Styles",
    locked: "Locked",
    unlockPro: "Unlock Pro →",
    walletTitle: "Wallet",
    walletSubtitle: "Your collections and assets",
    myCollections: "My Collections",
    balance: "Balance",
    forSale: "For Sale",
    sold: "Sold",
    items: "items",
    subTitle: "Mintify Pro",
    subSubtitle: "Unlock full potential",
    monthly: "Monthly",
    yearly: "Yearly",
    save: "−40%",
    proFeatures: ["All Pro Styles", "Unlimited NFTs", "Priority Generation", "Zero Marketplace Fee", "Collection Analytics", "24/7 Support"],
    freeFeatures: ["5 Free Styles", "Up to 10 NFTs / month", "Basic Marketplace"],
    buyPro: "Buy Pro",
    currentPlan: "Current Plan",
    freePlan: "Free",
    perMonth: "/ mo",
    perYear: "/ yr",
    price1: "$4.99",
    price2: "$34.99",
  },
};

export const NFT_IMG_1 = "https://cdn.poehali.dev/projects/007c67e7-c769-42c7-94cb-a7248dcc5c6f/files/1a6b371b-f4a4-4027-87f7-a90f1a3e9e73.jpg";
export const NFT_IMG_2 = "https://cdn.poehali.dev/projects/007c67e7-c769-42c7-94cb-a7248dcc5c6f/files/838d3d98-c2da-4c55-9122-3e5cdc04e62d.jpg";
export const NFT_IMG_3 = "https://cdn.poehali.dev/projects/007c67e7-c769-42c7-94cb-a7248dcc5c6f/files/fc4ed088-8d2e-45e9-8011-5844e114ed69.jpg";

export const FREE_STYLES = [
  { id: 1, name: "Geometric", nameRu: "Геометрия", emoji: "◆", color: "from-teal-500 to-cyan-600" },
  { id: 2, name: "Abstract", nameRu: "Абстракция", emoji: "◉", color: "from-blue-500 to-indigo-600" },
  { id: 3, name: "Pixel Art", nameRu: "Пиксель", emoji: "⬛", color: "from-emerald-500 to-teal-600" },
  { id: 4, name: "Nature", nameRu: "Природа", emoji: "◈", color: "from-green-500 to-emerald-600" },
  { id: 5, name: "Minimal", nameRu: "Минимал", emoji: "○", color: "from-slate-500 to-zinc-600" },
];

export const PRO_STYLES = [
  { id: 6, name: "Cyberpunk", nameRu: "Киберпанк", emoji: "◈", color: "from-purple-500 to-pink-600" },
  { id: 7, name: "Portraits", nameRu: "Портреты", emoji: "◎", color: "from-orange-500 to-red-600" },
  { id: 8, name: "Surreal", nameRu: "Сюрреализм", emoji: "◇", color: "from-fuchsia-500 to-purple-600" },
  { id: 9, name: "3D Art", nameRu: "3D арт", emoji: "⬡", color: "from-yellow-500 to-orange-600" },
  { id: 10, name: "Anime", nameRu: "Аниме", emoji: "◉", color: "from-pink-500 to-rose-600" },
];

export const MY_COLLECTIONS = [
  { id: 1, name: "Genesis Series", count: 10, img: NFT_IMG_1, price: "0.12 ETH", forSale: 3 },
  { id: 2, name: "Abstract Minds", count: 5, img: NFT_IMG_2, price: "0.08 ETH", forSale: 1 },
];
